---
version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      - GITBUCKET_PORT=8080
      - GITBUCKET_HOME=/gitbucket

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry

volumes:
  gitbucket_data:
  registry_data:
